### ISSUE TITLE
Our higher-order function optimizations don't work if the passed-in function closes over TraceReals

### ISSUE THREAD

**Issue by jrevels** [jrevels/ReverseDiffPrototype.jl#16]
```julia
julia> using ReverseDiffPrototype; const RDP = ReverseDiffPrototype;

julia> function f(x)
           a = one(eltype(x))
           return sum(map(i -> a * i, x))
       end
f (generic function with 1 method)

julia> RDP.gradient!(zeros(3), f, rand(3)) # wrong, should be all ones
3-element Array{Float64,1}:
 0.823614
 0.459833
 0.581877
```

Note that we could replace `a = one(eltype(x))` with something like `a = x[1]`, and the bug would persist. 

The closed-over `TraceReal` is causing each application of the closure to be written to the trace, laying down incorrect nodes that get accumulated in the reverse pass.  It's a perturbation-confusion-esque bug, but one that we're inducing on ourselves instead of it being induced by competing differentiation operators. 

Not only does it give the wrong answer, but it also kind of defeats the point of the optimization (to elide the tracing of the closure application).

I'm unsure how we can resolve this short of scrubbing the closure for `TraceReal`s, just as we'd have to do to fix JuliaDiff/ForwardDiff.jl#83. 

@mlubin any ideas?

**Comment by jrevels** [comment]
So after thinking about this for a bit (I actually discovered it yesterday), and drawing on a little bit of experience from JuliaDiff/ForwardDiff.jl#83, I think the safest and most tenable approach is to simply not apply the unsafe optimizations by default, and instead provide users an `@optdiff` macro (or something) which can be used to assert that it is safe to perform an AD optimization based on context.

Note that it really would have to be an *unchecked* user-assertion; I don't think you can adequately check for function purity at macro-time (well, maybe you could, but it would probably be really messy/fragile).  If Julia ever gets better support for introspecting function purity (an `ispure` trait or something), we might enable the optimization for pure functions automatically.

Anyway, requiring a directive isn't the most elegant solution, but it would at least solve the problem and still allow users to access the optimization.

**Comment by mlubin** [comment]
What are the unsafe optimizations?

**Comment by jrevels** [comment]
> What are the unsafe optimizations?

See [here](https://github.com/jrevels/ReverseDiffPrototype.jl/blob/master/src/array.jl#L43).

We overload `map`/`broadcast` for `AbstractArray{T <: TraceReal}` so that we can skip writing a bunch of nodes to the tape. Instead, we get the derivatives in the forward pass using arrays of `Dual`s, and store the whole `map`/`broadcast` operation as a single "bulk" node (whose reverse pass behavior is defined [here](https://github.com/jrevels/ReverseDiffPrototype.jl/blob/master/src/trace.jl#L118)).

This optimization is unsafe if the function passed to `map`/`broadcast` closes over `TraceReal`s, because those `TraceReal`s will then unexpectedly write operations to the tape, where the optimization assumes that it's skipping though operations. 

Unfortunately, like perturbation confusion, it's probably not transparent for a user to predict when this kind of thing will happen. It's also hard to detect automatically, so we can't reliably warn users either.
