### ISSUE TITLE
Macro for univariate functions

### ISSUE THREAD

**Issue by jmxpearson** [jrevels/ReverseDiffPrototype.jl#5]
Matrix derivatives have complex indexing, but for defining univariate derivatives, it's nice to have a macro. Currently, most cases can be handled with ForwardDiff internally, but a macro that takes a derivative expression (or function?) and defines `record!` and `backprop!` would reduce some code repetition.

**Comment by jrevels** [comment]
Closing this issue, since this is now achieved by adding a derivative definition to Calculus, which [automatically adds it to ForwardDiff](http://www.juliadiff.org/ForwardDiff.jl/contributing.html#unary-functions-via-calculus-jl), which automatically adds it to here.
